services:

  backend:
    build:
      context: ./backend
    container_name: ai-backend
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    networks:
      - myapp-network

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: http://localhost:5000/api/v1
    container_name: ai-frontend
    depends_on:
      - backend
    ports:
      - "8080:3000"
    networks:
      - myapp-network

networks:
  myapp-network:
    driver: bridge