services:

  backend:
    image: 887731514442.dkr.ecr.us-east-1.amazonaws.com/ai-backend:${IMAGE_TAG}
    container_name: ai-backend
    env_file:
      - ./backend.env
    ports:
      - "5000:5000"
    networks:
      - myapp-network

  frontend:
    image: 887731514442.dkr.ecr.us-east-1.amazonaws.com/ai-frontend:${IMAGE_TAG}
    container_name: ai-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - myapp-network

networks:
  myapp-network:
    driver: bridge