name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build backend image
        run: docker build -t ai-backend:local ./backend

      - name: Build frontend image
        run: |
          docker build \
            --build-arg NEXT_PUBLIC_API_URL=http://localhost:5000/api/v1 \
            -t ai-frontend:local ./frontend

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag Docker images
        run: |
          docker tag ai-backend:local 887731514442.dkr.ecr.us-east-1.amazonaws.com/ai-backend:v1
          docker tag ai-frontend:local 887731514442.dkr.ecr.us-east-1.amazonaws.com/ai-frontend:v1

      - name: Push Docker images to ECR
        run: |
          docker push 887731514442.dkr.ecr.us-east-1.amazonaws.com/ai-backend:v1
          docker push 887731514442.dkr.ecr.us-east-1.amazonaws.com/ai-frontend:v1     